### ISSUE TITLE
Step 3 incorrect steps

### ISSUE THREAD

**Issue by ahaverty** [googlecodelabs/android-lifecycles#28]
Step 3, in section 'Update ChronoActivity' >step 2

1. That comment doesn't exist
2. The code should be `mElapsedTime.postValue(newValue);`

**Comment by sp0rk** [comment]
Yes. It should be fixed on https://codelabs.developers.google.com

**Comment by abhishekdewan101** [comment]
Seconding this, also mElapsedTime.setValue(newValue) throws the following error 

`FATAL EXCEPTION: Timer-0
                                                                                        Process: com.example.android.codelabs.lifecycle, PID: 16399
                                                                                        java.lang.IllegalStateException: Cannot invoke setValue on a background thread
                                                                                            at android.arch.lifecycle.LiveData.assertMainThread(LiveData.java:406)
                                                                                            at android.arch.lifecycle.LiveData.setValue(LiveData.java:291)
                                                                                            at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
                                                                                            at com.example.android.lifecycles.step3_solution.LiveDataTimerViewModel$1.run(LiveDataTimerViewModel.java:48)
                                                                                            at java.util.TimerThread.mainLoop(Timer.java:555)
                                                                                            at java.util.TimerThread.run(Timer.java:505)`

**Comment by pedrovarela86** [comment]
this easily can be changed to setPostValue

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback! Fixing this comment now in an upcoming re-publish of the codelab.

Note the error from `mElapsedTime.setValue(newValue)` was because `setValue` was used but it should have been [`postValue`](https://developer.android.com/reference/androidx/lifecycle/LiveData.html#postValue(T)).
