### ISSUE TITLE
Lifecycle got crash on Android 5.0.2

### ISSUE THREAD

**Issue by AlanCheen** [googlecodelabs/android-lifecycles#49]
Im using Lifecycle  and got a lot of crash on Android 5.0.2 devices

crash log 

Caused by: java.lang.IllegalArgumentException
	at android.arch.lifecycle.LifecycleRegistry.downEvent(SourceFile:233)
	at android.arch.lifecycle.LifecycleRegistry.backwardPass(SourceFile:284)
	at android.arch.lifecycle.LifecycleRegistry.sync(SourceFile:299)
	at android.arch.lifecycle.LifecycleRegistry.handleLifecycleEvent(SourceFile:120)
	at android.arch.lifecycle.ReportFragment.dispatch(SourceFile:122)
	at android.arch.lifecycle.ReportFragment.onDestroy(SourceFile:107)
	at android.app.Fragment.performDestroy(Fragment.java:2266)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1017)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1049)
	at android.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:1897)
	at android.app.Activity.performDestroy(Activity.java:6111)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1140)
	at android.taobao.atlas.runtime.InstrumentationHook.callActivityOnDestroy(SourceFile:1069)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3761)
	... 12 more

I have no idea why we got this crash , any ideas? 

Thanks in advance

**Comment by jabubake** [comment]
@AlanCheen : We recently updated the project. Can you please try with Android Studio 3.2.1 (stable) and let us know if you are still running into the same issue ?

**Comment by AlanCheen** [comment]
Ok , i will try. Thanks.
